### ISSUE TITLE
Option to specify the AJAX fragment URL to pull in

### ISSUE THREAD

**Issue by toddparker** [filamentgroup/dialog#22]
Right now, we always use the `href` to populate the dialog and assume the server is smart enough to either respond with a full page or just a fragment.
`<a href="/path/to/fullpage.html" data-dialog-link>Open in dialog</a>`

It would be nice if we could optionally specify the fragment URL as an attribute like `data-ajax-href`:
`<a href="/path/to/fullpage.html" data-dialog-link data-ajax-href="fragment.html">Open in dialog</a>`

**Comment by scottjehl** [comment]
Should we just implement this via a value for `data-dialog-link`? We currently check for that attribute's presence to decide if it's a dialog link, but we never look for its value.

Proposed markup would be:
```
<a href="/path/to/fullpage.html" data-dialog-link="path/to/fragment.html">Open in dialog</a>
```

**Comment by johnbender** [comment]
If that works I'm all for it.

👍

**Comment by scottjehl** [comment]
@toddparker ya?
