### ISSUE TITLE
dialog history branch bug: 

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/dialog#32]
1. Go to this non-history dialog url: http://history.origin.dialog.fgview.com/demos/#mydialog-3-dialog
2. scroll to the first non-history dialog link, click it
3. hit back button

Expected: should close dialog
Result: goes back to whereever you came from

**Comment by johnbender** [comment]
@scottjehl 

I noticed that the `nohistory` dialog example does respond to the back button on the demo page, but not forward. That makes sense on some level but I wanted to double check with you on that.

**Comment by scottjehl** [comment]
yep - no-history is all about deep linking and reopening or not. But closing is always the same.
