### ISSUE TITLE
Manage focus after closing dialog

### ISSUE THREAD

**Issue by weboverhauls** [filamentgroup/dialog#40]
After the dialog is closed, the keyboard focus is lost. This is a very poor experience for keyboard user (sighted or not) as they lose their place on the screen.

Recommend returning the focus to the control which opened it.

WCAG 2.4.3 — Focus Order

**Comment by patrickhlauke** [comment]
hah, you beat me to the punch https://twitter.com/patrick_h_lauke/status/827288493873385472

**Comment by scottjehl** [comment]
Thanks! Will do.
