### ISSUE TITLE
Provide label for dialog

### ISSUE THREAD

**Issue by weboverhauls** [filamentgroup/dialog#41]
Provide a heading/label/title for the dialog to inform the user the purpose of the dialog. This is especially desirable for screen reader users. 

If the label is visible (i.e. a typical heading), use aria-labelledby on the containing element (the one that has role=dialog) to associate for screen reader users. 

If the design calls for the label to not be visible, use aria-label on the containing element.

**Comment by scottjehl** [comment]
Thanks. Makes sense. The dialog script is not prescriptive on this, so I gather this may mostly be addressed by making our demo HTML a little stronger... 

We'll take a look thanks!
