### ISSUE TITLE
Dialog no background documentation

### ISSUE THREAD

**Issue by matthewkubej** [filamentgroup/dialog#42]
The documentation for providing no background to dialogs says to use the `data-dialog-nobg` attribute.  However, it appears dialog.js is looking for `data-nobg` on line 33 to provide this functionality.

Just wanted to provide a heads up, because I ran into this while I was trying to leverage this feature.   It seems `data-nobg` does the trick.

**Comment by scottjehl** [comment]
Thanks! See the "Modal and non-modal" section in the docs. It's covered in there I think.
https://master-origin-dialog.fgview.com/demos/

**Comment by matthewkubej** [comment]
Hi Scott,

I was trying to point out that the documentation does not reflect what is implemented.  

It seems `data-dialog-nobg` does not work, but `data-nobg` does based on the implementation in dialog.js.

**Comment by scottjehl** [comment]
ah! Sorry about that. Thanks for restating. I somehow read that issue incorrectly. We'll take a look.

**Comment by matthewkubej** [comment]
No worries!  I could have stated it more clearly initially.  Thanks Scott!

**Comment by scottjehl** [comment]
fixed in https://github.com/filamentgroup/dialog/commit/765ab902ad9fcd6c6c40214aabfaf71fce5b24e1
